### PR TITLE
Live character count

### PR DESCRIPTION
**Pull request by rgantzos**
Screenshot 2023-06-18 at 8 33 21 AM
Screenshot 2023-06-18 at 8 33 35 AM
Screenshot 2023-06-18 at 8 33 51 AM

### CODE REVIEW

**Review by callumjt — APPROVED** [review]
cool

**Comment by MaterArc** [comment]
Nice :)

**Comment by MaterArc** [comment]
Does this also work on project titles? I'm actually curious...

**Comment by rgantzos** [comment]
> Does this also work on project titles? I'm actually curious...

Not yet, thanks for reminding me! I’ll add that for studio and project titles.

**Comment by MaterArc** [comment]
Cool, np!

**Pull request merged**
