### PR TITLE
Country Flag on Profile

### PR DESCRIPTION
**Pull request by MaterArc**
Adds flag emojis near selected locations on profile pages.
Screenshot 2023-11-01 at 8 49 37 PM

### CODE REVIEW

**Review by callumjt — APPROVED** [review]
thats uhh prettyy cool and epic and everything else i cant think of anything else to put (i have the best reviews :))

**Comment by MaterArc** [comment]
> thats uhh prettyy cool and epic and everything else i cant think of anything else to put (i have the best reviews :))

Thanks, callum!

**Review by rgantzos — COMMENTED** [review]
The folder name itself does not match the `features.json` file and does not match feature ID requirements. It should be all lowercase and they should be the same.

**Review by rgantzos — CHANGES_REQUESTED** [review]
The folder name itself does not match the features.json file and does not match feature ID requirements. It should be all lowercase and they should be the same.

**Pull request closed without merging**
