### PR TITLE
Change Icons

### PR DESCRIPTION
**Pull request by Daniel4-Scratch**
Changed
Screen Shot 2022-07-05 at 7 34 25 pm
to
Screen Shot 2022-07-05 at 7 34 34 pm

Reason:
The st logo without the circle may look disgusting on some user's browsers depending on there theme of the. The one with the orange circle adds more contrast to the logo and makes it stand out.
Screen Shot 2022-07-05 at 7 37 13 pm. Screen Shot 2022-07-05 at 7 38 18 pm
The logo without the orange circle doesnt stand out on the white background, while the one with the orange circle stands out on both backgrounds

### CODE REVIEW

**Comment by rgantzosonscratch** [comment]
We don’t use icons 1 and 2 anymore. We have switched to icon 3.

**Comment by Daniel4-Scratch** [comment]
4A9A6750-FCF4-4CA0-8C4D-975F9A74B89E
You are currently are using the logo on the left, it won’t look good on all backgrounds. So I’ve changed it to the one on the right

**Comment by rgantzosonscratch** [comment]
> 4A9A6750-FCF4-4CA0-8C4D-975F9A74B89E
> You are currently are using the logo on the left, it won’t look good on all backgrounds. So I’ve changed it to the one on the right

I know, but you updated `logo1.png` and `logo2.png`, even though we no longer use those and have moved on to `logo3.png`.

**Comment by Daniel4-Scratch** [comment]
But I updated the `icon16`, `icon48` and `icon128`.

**Comment by rgantzosonscratch** [comment]
Yes, but the popup uses `logo3.png`, not any of those files. We also use it as our default icon I believe.

**Comment by rgantzosonscratch** [comment]
@Daniel4-Scratch would this be for the popup too, or just the extension page?

**Comment by Daniel4-Scratch** [comment]
i changed logo 3

**Review by rgantzosonscratch — CHANGES_REQUESTED** [review]
We don't need the `.DS_Store` file.

**Comment by rgantzosonscratch** [comment]
Also, this won't work since the beta version uses purple as its background color.

**Comment by Daniel4-Scratch** [comment]
> Also, this won't work since the beta version uses purple as its background color.

But if we at least change the icon that shows in the browser nav bar that would be good

**Pull request closed without merging**
