### PR TITLE
Changed so that style element is appended at head not body, as it isnt after the standard.

### PR DESCRIPTION
**Pull request by nikeedev**
Changed so that style element is appended at head not body, as it isnt after the standard.

### CODE REVIEW

**Comment by nikeedev** [comment]
IM PR #500!!!

**Review by nikeedev — COMMENTED** [review]
review!

**Comment by nikeedev** [comment]
@rgantzos

**Comment by callumjt** [comment]
hmmm, i dont see a point in this?

**Comment by Wilamaxin** [comment]
Actually, the better option is to update this feature to v2 and just use `style.css` to insert the CSS into the page.

**Comment by rgantzos** [comment]
> Actually, the better option is to update this feature to v2 and just use `style.css` to insert the CSS into the page.

I agree, then we can make it dynamic without needing any JavaScript.

**Comment by rgantzos** [comment]
@nikeedev Would you be willing to make this in Feature v2?

**Comment by nikeedev** [comment]
> @nikeedev Would you be willing to make this in Feature v2?

wdym?

**Comment by rgantzos** [comment]
> > @nikeedev Would you be willing to make this in Feature v2?
> 
> wdym?

https://docs.scratchtools.app/blog/v2

**Comment by nikeedev** [comment]
> https://docs.scratchtools.app/blog/v2

Oh thanks! But now I understood what you meant. Will change it soon!

**Comment by nikeedev** [comment]
But it looks like other features also need to be updated to v2?

**Comment by MaterArc** [comment]
> But it looks like other features also need to be updated to v2?

Yes, that is true. However, the comment is particularly pertaining to this pull request to get updated. Other features will be updated soon.

**Comment by rgantzos** [comment]
> But it looks like other features also need to be updated to v2?

Other features are slowly getting moved over to the new version as well. However, if we're going to make changes to a feature, we might as well also convert it to the new version. Converting it to the new version also means that we wouldn't need to deal with where to put the style element, since ScratchTools does that for us.

**Comment by nikeedev** [comment]
Converted to v2, and works too.

**Review by MaterArc — APPROVED** [review]
Nice, thanks for converting it!

**Comment by nikeedev** [comment]
> Nice, thanks for converting it!

No problem!

**Pull request merged**
