### PR TITLE
Update mit.txt

### PR DESCRIPTION
**Pull request by MaterArc**
In order for MIT license to work, you need to have the right of copy line (line that shows who the code belongs to and who is up keeping the project).

### CODE REVIEW

**Comment by GarboMuffin** [comment]
My understanding was that this license was added in reference to code included in https://github.com/forkphorus/cat-plus/, thus to follow this license:

```
Copyright (c) 2019 Thomas Weber

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

**The above copyright notice** and this permission notice shall be included in all
copies or substantial portions of the Software.

...
```

You need to include the notice referred to by the license, which is:

```
Copyright (c) 2019 Thomas Weber
```

somewhere along with the license

**Comment by MaterArc** [comment]
Yeah, that makes sense...

> My understanding was that this license was added in reference to code included from https://github.com/forkphorus/cat-plus/, thus to follow its license:
> 
> ```
> Copyright (c) 2019 Thomas Weber
> 
> Permission is hereby granted, free of charge, to any person obtaining a copy
> of this software and associated documentation files (the "Software"), to deal
> in the Software without restriction, including without limitation the rights
> to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
> copies of the Software, and to permit persons to whom the Software is
> furnished to do so, subject to the following conditions:
> 
> **The above copyright notice** and this permission notice shall be included in all
> copies or substantial portions of the Software.
> 
> ...
> ```
> 
> You need to include the notice referred to by the license, which is:
> 
> ```
> Copyright (c) 2019 Thomas Weber
> ```
> 
> somewhere along with the license
> 
> replacing it with your a notice attributing other people does not satisfy this requirement

**Comment by MaterArc** [comment]
> My understanding was that this license was added in reference to code included from https://github.com/forkphorus/cat-plus/, thus to follow its license:
> 
> ```
> Copyright (c) 2019 Thomas Weber
> 
> Permission is hereby granted, free of charge, to any person obtaining a copy
> of this software and associated documentation files (the "Software"), to deal
> in the Software without restriction, including without limitation the rights
> to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
> copies of the Software, and to permit persons to whom the Software is
> furnished to do so, subject to the following conditions:
> 
> **The above copyright notice** and this permission notice shall be included in all
> copies or substantial portions of the Software.
> 
> ...
> ```
> 
> You need to include the notice referred to by the license, which is:
> 
> ```
> Copyright (c) 2019 Thomas Weber
> ```
> 
> somewhere along with the license
> 
> replacing it with your a notice attributing other people does not satisfy this requirement

Wait, so the pr that I made doesn't work?

**Comment by rgantzos** [comment]
@MaterArc the license isn’t there to credit myself, it’s due to the libraries and other repositories that we used, such as GarboMuffin’s cat-plus repository. All code that I contribute (that I wrote myself) was directly contributed here.

**Comment by callumjt** [comment]
i understand none of this :D

**Pull request closed without merging**
