### PR TITLE
anti-generic.js fix

### PR DESCRIPTION
**Pull request by aidinjk**
You can merge and add more keywords as needed.

### CODE REVIEW

**Comment by aidinjk** [comment]
Ignore the last one, my features.js was outdated

**Comment by aidinjk** [comment]
https://user-images.githubusercontent.com/69284371/202538832-4960f037-f486-487b-8609-e75c135dff6e.MOV

Examples of the new keywords in action

**Comment by aidinjk** [comment]
Sorry, I like changing things a lot

**Comment by aidinjk** [comment]
Xd

**Review by rgantzos — APPROVED** [review]

**Pull request merged**
