### PR TITLE
sidebar updates

### PR DESCRIPTION
**Pull request by callumjt**
new stuff:
works when not logged in
sign out button when logged in

im wanting to add interactions when hovered over the buttons but i dont have time atm so ill add it tmrw

### CODE REVIEW

**Comment by MaterArc** [comment]
Looks good to me.

**Comment by callumjt** [comment]
> Looks good to me.

thank you great friend :)

**Comment by callumjt** [comment]
made the text color orange when hovered

**Comment by MaterArc** [comment]
ok

**Comment by callumjt** [comment]
@rgantzos do you think you could review this :)

**Review by rgantzos — APPROVED** [review]

**Pull request merged**
