### PR TITLE
Readme Update

### PR DESCRIPTION
**Pull request by AnderMendoza**
I have organized the header of your readme file by adding a short description and navigation links on your repository.

Please add my file to your repository with tag hacktoberfest. Thank you.

### CODE REVIEW

**Review by rgantzosonscratch — CHANGES_REQUESTED** [review]
You should replace the links to the Issues section with https://github.com/STForScratch/ScratchTools/issues/new?assignees=&labels=feature&template=feature_request.md&title= and https://github.com/STForScratch/ScratchTools/issues/new?assignees=&labels=feature&template=bug_report.md&title=

**Comment by AnderMendoza** [comment]
What else could I do to get my merger request accepted?

**Comment by rgantzosonscratch** [comment]
> What else could I do to get my merger request accepted?

Check out the issue I just linked and unlinked for a future PR. For now, I’ll merge this one.

**Review by rgantzosonscratch — APPROVED** [review]
Looks good!

**Comment by AnderMendoza** [comment]
I could put the tag hacktoberfest. It would help me a lot to complete my progress in this event, thanks again.

**Comment by RedGuy12** [comment]
Hacktoberfest PRs aren't counted until after Oct 1st...

**Comment by AnderMendoza** [comment]
Could I come back on October 1 to ask them to tag them then?

**Comment by rgantzosonscratch** [comment]
> Could I come back on October 1 to ask them to tag them then?

Feel free to come back on October 1st and make more PR’s.

**Comment by RedGuy12** [comment]
> Could I come back on October 1 to ask them to tag them then?

Hacktoberfest only counts PRs made after October 1st.

**Pull request merged**
