### PR TITLE
Safari extension

### PR DESCRIPTION
**Pull request by b5i**
Hello, here is the Xcode project of the extension, tell me if I have to add the .app file (binaries).

### CODE REVIEW

**Comment by b5i** [comment]
Little problem with sources location, don't merge it now.

**Comment by rgantzosonscratch** [comment]
We’re an open source extension, and it costs a lot of money to publish Safari extensions. We will look into it.

**Comment by b5i** [comment]
> We’re an open source extension, and it costs a lot of money to publish Safari extensions. We will look into it.

Of course, but people can install by double-clicking on an .app file and it installs automatically the extension (README file)

**Comment by b5i** [comment]
Ok now macOS is ready: just type `make` for macOS and `make ios` for iOS/iPadOS app.

**Comment by rgantzosonscratch** [comment]
When I test this with Xcode installed, none of the features are actually working. I'm going to do more tests.

**Comment by b5i** [comment]
> When I test this with Xcode installed, none of the features are actually working. I'm going to do more tests.

It seems there is some problems with the scratch, I'm getting "Unexpected end of script" in main.js in the web console

**Comment by rgantzosonscratch** [comment]
> > When I test this with Xcode installed, none of the features are actually working. I'm going to do more tests.
> 
> It seems there is some problems with the scratch, I'm getting "Unexpected end of script" in main.js in the web console

That's not the issue, you just have to pull the recent commits to your fork. That has already been fixed.

**Comment by b5i** [comment]
> > > When I test this with Xcode installed, none of the features are actually working. I'm going to do more tests.
> > 
> > 
> > It seems there is some problems with the scratch, I'm getting "Unexpected end of script" in main.js in the web console
> 
> That's not the issue, you just have to pull the recent commits to your fork. That has already been fixed.

Done, but this time the extension works as it has to: (activated opacity button)
Capture d’écran 2022-10-02 à 4 52 42 PM

**Review by mistysloth — COMMENTED** [review]
All the features work for me, but I'm not giving this a full approve because it doesn't work for everyone.

**Comment by rgantzosonscratch** [comment]
> All the features work for me, but I'm not giving this a full approve because it doesn't work for everyone.

I could just be doing something wrong, but I’m going to have to be the one who explains it to everyone else so that means I should figure it out before merging.

**Comment by b5i** [comment]
> > All the features work for me, but I'm not giving this a full approve because it doesn't work for everyone.
> 
> I could just be doing something wrong, but I’m going to have to be the one who explains it to everyone else so that means I should figure it out before merging.

Ok so we need to figure out why it does not work in your case. When you say that it does not work, in which way?

**Comment by rgantzosonscratch** [comment]
> > > All the features work for me, but I'm not giving this a full approve because it doesn't work for everyone.
> > 
> > 
> > I could just be doing something wrong, but I’m going to have to be the one who explains it to everyone else so that means I should figure it out before merging.
> 
> Ok so we need to figure out why it does not work in your case. When you say that it does not work, in which way?

Screen Shot 2022-10-03 at 9 13 22 AM
It returns an error whenever I try and use `make`. Is the folder name important? I'm running the terminal in my folder.

**Comment by rgantzosonscratch** [comment]
> Ok could you show before the help message from Xcode please?
> […](#)
> Le 3 oct. 2022 à 18:14, rgantzos ***@***.***> a écrit : All the features work for me, but I'm not giving this a full approve because it doesn't work for everyone. I could just be doing something wrong, but I’m going to have to be the one who explains it to everyone else so that means I should figure it out before merging. Ok so we need to figure out why it does not work in your case. When you say that it does not work, in which way? It returns an error whenever I try and use `make`. Is the folder name important? I'm running the terminal in my folder. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.

Screen Shot 2022-10-03 at 9 27 53 AM

**Comment by b5i** [comment]
Ok I see, your directory contains a space and the make does not like it.

**Review by rgantzosonscratch — COMMENTED** [review]
What does this do?

**Comment by b5i** [comment]
> What does this do? (Your newest fix)

It assure that the path (even with a space) will be considered as one argument instead of two.

**Comment by rgantzosonscratch** [comment]
> What does this do? (Your newest fix)

Oh, alright 

> > What does this do? (Your newest fix)
> 
> It assure that the path (even with a space) will be considered as one argument instead of two.

Oh alright thanks, I’ll check it out soon. We’re planning on releasing this for our big 1,000 user event, but this will likely be merged before then.

**Review by rgantzosonscratch — APPROVED** [review]

**Pull request merged**
