### PR TITLE
THE FORBIDDEN SECRET

### PR DESCRIPTION
**Pull request by SecretAgent55**
[redacted]

### CODE REVIEW

**Review by rgantzosonscratch — COMMENTED** [review]
The review has been complete, thank you for your contribution! This feature has been approved.

**Comment by rgantzosonscratch** [comment]
It doesn’t work on 2.0 pages.

**Comment by SecretAgent55** [comment]
try: document.getElementsByTagName('body')[0].style.transform = 'rotate(180deg)';

**Comment by SecretAgent55** [comment]
I don't have edit access

**Pull request merged**
