### PR TITLE
Add feature to turn unlinked links into linked ones

### PR DESCRIPTION
**Pull request by ScolderCreations**
Self explanatory. Untested though, let me know if anything goes wrong.

### CODE REVIEW

**Comment by rgantzosonscratch** [comment]
The way you did this looks cool, however it won't work due to 3 issues:
1. Using innerHTML might be dangerous based on the way you're using it (I don't think it is but there's a possibility).
2. Because of this, no images will load and page JavaScript won't run.
3. What if you press load more comments or something? Then the new elements that are created won't include <a> tags for their turbowarp links.

**Comment by ScolderCreations** [comment]
> The way you did this looks cool, however it won't work due to 3 issues:
> 
> 1. Using innerHTML might be dangerous based on the way you're using it (I don't think it is but there's a possibility).
> 2. Because of this, no images will load and page JavaScript won't run.
> 3. What if you press load more comments or something? Then the new elements that are created won't include  tags for their turbowarp links.

Good points. 
Number 1 probably won’t be a problem since the only content it can insert must be a turbowarp.org link containing numbers, and there’s no wildcard characters (which would be dangerous.)
Number 2 makes a bit of sense, I’ll make it wait for everything else.
Number 3: How would we fix this?

**Comment by rgantzosonscratch** [comment]
I'm not completely sure about how you can linkify an element, but I'll look into it. I recommend doing something like this:
```
document.querySelectorAll('.content').forEach(function(el) {
   linkify(el)
})
```
However, like I said, I'm not sure how to linkify elements so the `linkify` function won't do anything. For now, I'll just look for a way to do this.

**Comment by ScolderCreations** [comment]
I intended for this to be used with project descriptions, mainly. If it works with some comments that’s just a bonus.

**Comment by rgantzosonscratch** [comment]
@ScolderCreations We now have a `ScratchTools.waitForElements(selector, callback)` API. That should make it so this works perfeclty.

**Comment by ScolderCreations** [comment]
> @ScolderCreations We now have a `ScratchTools.waitForElements(selector, callback)` API. That should make it so this works perfeclty.

Great. I’ll get to work…

**Comment by ScolderCreations** [comment]
@rgantzosonscratch Should work now.

**Comment by rgantzosonscratch** [comment]
> @rgantzosonscratch Should work now.

Would you be able to make it work for all links, not just Turbowarp?

**Comment by ScolderCreations** [comment]
> > @/rgantzosonscratch Should work now.
> 
> Would you be able to make it work for all links, not just Turbowarp?

Yeah, give me  a moment…

**Comment by ScolderCreations** [comment]
@rgantzosonscratch Should work now.

**Comment by rgantzosonscratch** [comment]
> @rgantzosonscratch Should work now.

Alright thanks, I’ll test it soon.

**Comment by rgantzosonscratch** [comment]
@ScolderCreations the API waitForElements requires an ID.

**Comment by ScolderCreations** [comment]
> @ScolderCreations the API waitForElements requires an ID.

oh

**Comment by rgantzosonscratch** [comment]
Alright, so you're defining "el", but you only use "e" when setting innerText. Also, innerText and innerHTML aren't the same thing, and several arguments in ScratchTools.waitForElements() have not been defined.

**Comment by ScolderCreations** [comment]
> Alright, so you're defining "el", but you only use "e" when setting innerText. Also, innerText and innerHTML aren't the same thing, and several arguments in ScratchTools.waitForElements() have not been defined.

What is the “id” argument?

**Comment by rgantzosonscratch** [comment]
> > Alright, so you're defining "el", but you only use "e" when setting innerText. Also, innerText and innerHTML aren't the same thing, and several arguments in ScratchTools.waitForElements() have not been defined.
> 
> What is the “id” argument?

Just a string that classifies between which part of features are looking for certain elements, and each one can only be used for one query each.

**Comment by ScolderCreations** [comment]
@rgantzosonscratch how bout now?

**Comment by rgantzosonscratch** [comment]
> @rgantzosonscratch how bout now?

Still doesn't work.

**Comment by veloce-vasta** [comment]
> > 3. What if you press load more comments or something? Then the new elements that are created won't include  tags for their turbowarp links.
> 
> Number 3: How would we fix this?

Say `lm` is the load more button
`lm.addEventListener("click", linkify())`

**Comment by rgantzos** [comment]
> > > 5\. What if you press load more comments or something? Then the new elements that are created won't include  tags for their turbowarp links.
> > 
> > 
> > Number 3: How would we fix this?
> 
> Say `lm` is the load more button `lm.addEventListener("click", linkify())`

The [waitForElements](https://docs.scratchtools.app/docs/api/waitforelements) API works just fine for this.

**Pull request closed without merging**
