### PR TITLE
Clicker Game

### PR DESCRIPTION
**Pull request by Daniel4-Scratch**

### CODE REVIEW

**Comment by StioStudio** [comment]
What....

**Comment by Daniel4-Scratch** [comment]
@StioStudio wdym "what?"

**Comment by StioStudio** [comment]
> @StioStudio wdym "what?"

Umm did not expect a game inside of scratch tools

**Comment by Daniel4-Scratch** [comment]
@rgantzos this was a clicker easter egg i made awhile ago, i was going to add more but didnt end up doing so. It is in a functioning state for release. I will add the shop plus more features some other time

**Pull request merged**
