### PR TITLE
Better scollbar

### PR DESCRIPTION
**Pull request by StioStudio**
I did not like the old scrollbar, so I changed it to what the "scratch 4" addon (to SA) will look like.

### CODE REVIEW

**Comment by callumjt** [comment]
Imo there shouldn't be a scroll bar on each of the features

**Comment by StioStudio** [comment]
> Imo there shouldn't be a scroll bar on each of the features

What do you mean?

**Review by rgantzos — CHANGES_REQUESTED** [review]
It's really wide and takes up too much space. It shouldn't be this noticeable, and also shouldn't display when the user doesn't need it.
Screenshot 2023-05-28 at 7 52 52 AM

**Comment by StioStudio** [comment]
> It's really wide and takes up too much space. It shouldn't be this noticeable, and also shouldn't display when the user doesn't need it. Screenshot 2023-05-28 at 7 52 52 AM

Turn on dark mode please. I forgot to make it work in light mode

**Comment by rgantzos** [comment]
> > It's really wide and takes up too much space. It shouldn't be this noticeable, and also shouldn't display when the user doesn't need it. Screenshot 2023-05-28 at 7 52 52 AM
> 
> Turn on dark mode please. I forgot to make it work in light mode

It's still too big and noticeable.

**Comment by StioStudio** [comment]
It is supposed to look like this
image

**Comment by StioStudio** [comment]
> > > It's really wide and takes up too much space. It shouldn't be this noticeable, and also shouldn't display when the user doesn't need it. Screenshot 2023-05-28 at 7 52 52 AM
> > 
> > 
> > Turn on dark mode please. I forgot to make it work in light mode
> 
> It's still too big and noticeable.

Can just set the width lower

**Pull request closed without merging**
